version: "3.7"
services:
  application:
    image: spring-boot-mysql-app
    ports:
      - "8080:8080"
    networks:
      - springboot-db-net
    environment:
      - SPRING_DATASOURCE_URL:jdbc:mysql://mysqldb:3306/sbms
      - SPRING_DATASOURCE_USERNAME:root
      - SPRING_DATASOURCE_PASSWORD:Tanushri
    depends_on:
      - mysqldb
    volumes:
      - /data/springboot-app
  mysqldb:
    image: mysql:8.0
    networks:
      - springboot-db-net
    ports:
     - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Tanushri
      - MYSQL_DATABASE=sbms
    volumes:
      - /data/mysql
networks:
  springboot-db-net:
