version: "3.7"
services:
  application:
    image: spring-boot-mysql-app
    ports:
      - "8080:8080"
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    volumes:
      - springboot-app-data:/data/springboot-app
    entrypoint: ["/wait-for-it.sh", "mysqldb:3306", "--", "java", "-jar", "/spring-boot-mysql.jar"]

  mysqldb:
    image: mysql:8.0
    networks:
      - springboot-db-net
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sbms1
    volumes:
      - mysql-data:/data/mysql

networks:
  springboot-db-net:
    driver: bridge

volumes:
  springboot-app-data:
  mysql-data:


     
